/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

  /**
   * http://tools.android.com
   */
  const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
      Versions.constraintlayout

  const val databinding_adapters: String = "androidx.databinding:databinding-adapters:" +
      Versions.androidx_databinding

  /**
   * https://developer.android.com/studio
   */
  const val databinding_common: String = "androidx.databinding:databinding-common:" +
      Versions.androidx_databinding

  /**
   * https://developer.android.com/studio
   */
  const val databinding_compiler: String = "androidx.databinding:databinding-compiler:" +
      Versions.androidx_databinding

  const val databinding_runtime: String = "androidx.databinding:databinding-runtime:" +
      Versions.androidx_databinding

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val lifecycle_compiler: String = "androidx.lifecycle:lifecycle-compiler:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
      Versions.navigation_fragment_ktx

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val navigation_safe_args_gradle_plugin: String =
      "androidx.navigation:navigation-safe-args-gradle-plugin:" +
      Versions.navigation_safe_args_gradle_plugin

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
      Versions.navigation_ui_ktx

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_compiler: String = "androidx.room:room-compiler:" + Versions.androidx_room

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_runtime: String = "androidx.room:room-runtime:" + Versions.androidx_room

  const val viewpager2: String = "androidx.viewpager2:viewpager2:" + Versions.viewpager2

  /**
   * https://developer.android.com/studio
   */
  const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

  /**
   * https://developer.android.com/studio
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
      Versions.com_android_tools_build_gradle

  /**
   * https://developer.android.com/studio
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  /**
   * https://github.com/Ferfalk/SimpleSearchView
   */
  const val simplesearchview: String = "com.github.Ferfalk:SimpleSearchView:" +
      Versions.simplesearchview

  /**
   * https://github.com/Clans/FloatingActionButton
   */
  const val fab: String = "com.github.clans:fab:" + Versions.fab

  /**
   * https://github.com/lecho/hellocharts-android
   */
  const val hellocharts_library: String = "com.github.lecho:hellocharts-library:" +
      Versions.hellocharts_library

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val material: String = "com.google.android.material:material:" + Versions.material

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android_processor: String = "com.google.dagger:dagger-android-processor:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android_support: String = "com.google.dagger:dagger-android-support:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

  const val firebase_auth: String = "com.google.firebase:firebase-auth:" + Versions.firebase_auth

  const val firebase_messaging: String = "com.google.firebase:firebase-messaging:" +
      Versions.firebase_messaging

  const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

  /**
   * https://github.com/karumi/Dexter
   */
  const val dexter: String = "com.karumi:dexter:" + Versions.dexter

  /**
   * http://github.com/square/leakcanary/
   */
  const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
      Versions.leakcanary_android

  /**
   * https://github.com/square/okhttp
   */
  const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
      Versions.logging_interceptor

  /**
   * https://github.com/square/retrofit/
   */
  const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit/
   */
  const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit/
   */
  const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  /**
   * https://github.com/grantland/android-autofittextview
   */
  const val autofittextview: String = "me.grantland:autofittextview:" + Versions.autofittextview

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions_runtime: String =
      "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_annotation_processing_gradle: String =
      "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://github.com/Kotlin/kotlinx.coroutines
   */
  const val kotlinx_coroutines_android: String =
      "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.org_jetbrains_kotlinx

  /**
   * https://github.com/Kotlin/kotlinx.coroutines
   */
  const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
      Versions.org_jetbrains_kotlinx
}
