
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val appcompat: String = "1.1.0-alpha04"

  const val constraintlayout: String = "1.1.3"

  const val androidx_databinding: String = "3.5.0"

  const val androidx_lifecycle: String = "2.2.0-alpha03"

  const val navigation_fragment_ktx: String = "2.1.0-alpha04"

  const val navigation_safe_args_gradle_plugin: String = "2.2.0-alpha01"

  const val navigation_ui_ktx: String = "2.1.0-alpha04"

  const val paging_runtime_ktx: String = "2.1.0"

  const val room_compiler: String = "2.2.0-alpha01"

  const val room_ktx: String = "2.2.0-beta01"

  const val room_runtime: String = "2.2.0-alpha01"

  const val viewpager2: String = "1.0.0-beta03"

  const val aapt2: String = "3.5.0-5435860"

  const val com_android_tools_build_gradle: String = "3.5.0"

  const val lint_gradle: String = "26.5.0"

  const val simplesearchview: String = "0.1.4"

  const val fab: String = "1.6.4"

  const val hellocharts_library: String = "1.5.8"

  const val material: String = "1.1.0-alpha06"

  const val com_google_dagger: String = "2.24"

  const val firebase_auth: String = "19.0.0"

  const val firebase_messaging: String = "20.0.0"

  const val google_services: String = "4.3.1"

  const val dexter: String = "5.0.0"

  const val leakcanary_android: String = "2.0-beta-3"

  const val logging_interceptor: String = "4.1.0"

  const val com_squareup_retrofit2: String = "2.6.1"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

  const val autofittextview: String = "0.2.1"

  const val org_jetbrains_kotlin: String = "1.3.50"

  const val org_jetbrains_kotlinx: String = "1.3.0"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6.1"

  const val gradleCurrentVersion: String = "5.4.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
